version: '3.8'
services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    volumes:
      - sql_server_data:/var/opt/mssql
  qdrant-db:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    container_name: api
    build:
      context: ./ai-chatbot-server/src/AI.Chatbot.Server
      dockerfile: Dockerfile
    ports:
      - "7043:8080"
      - "7243:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - "ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=AIChatbot;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=true"
      - "ConnectionStrings__Redis=redis:6379"
      - "OpenAI__ApiKey=your-openai-api-key" # Replace with your actual key
    depends_on:
      - sql-server-db
      - qdrant-db
      - redis

volumes:
  sql_server_data:
  qdrant_data:
  redis_data: