version: '3.8'
services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    volumes:
      - sql_server_data:/var/opt/mssql

volumes:
  sql_server_data: 